### ISSUE TITLE
Color reflecting cluster size/number instead of level

### ISSUE THREAD

**Issue by tiagobrc** [lazappi/clustree#20]
Hi, congrats on the excellent package,

I was wondering if it is possible to color the cluster nodes reflecting the size in the same way Seurat does. I did by hand in Illustrator to make my point more clear.

![rplot01](https://user-images.githubusercontent.com/12516337/43692055-14a45fd6-98f2-11e8-81c3-7873b666f6b4.png)

Thank you!

**Comment by lazappi** [comment]
Hi @tiagobrc 

Thanks for giving clustree a go!

You can do this by setting the `node_colour` option to `"cluster"`. Here is an example using the example Iris dataset:

```r
library(clustree)
clustree(iris_clusts, prefix = "K", node_colour = "cluster")
```

![cluster_colour](https://user-images.githubusercontent.com/6869320/43692860-2491d988-996e-11e8-8186-2bc47ef0449e.png)

As you can see this kind of half works, the nodes are coloured by the right variable, but it uses a continuous scale instead of a discrete one. That should be pretty easy to fix, I'll try to push something to the development version soon.

**Comment by lazappi** [comment]
Hi @tiagobrc 

I've just made a change to the development version that fixed this. Here is the output of the same Iris example using the development version (v0.2.2.9001):

```r
clustree(iris_clusts, prefix = "K", node_colour = "cluster")
```

![cluster_colour_fixed](https://user-images.githubusercontent.com/6869320/43693362-c1cae4b8-9970-11e8-8674-fad27a9cf521.png)

You can install the development version using.

```r
devtools::install_github("lazappi/clustree@develop")
```

**Comment by tiagobrc** [comment]
Amazing @lazappi! 

It worked very well.
Thank you so much for the quick implement. Very nice; it let me grasp the cluster tree from the perspective of Seurat. 


Best regards,

Tiago

**Comment by lazappi** [comment]
Great!

Just a word of caution of doing this. It could potentially be misleading to people looking at it as nodes with the same colour aren't necessarily related. For example in the image you originally posted Cluster 0 is mostly on the left of the tree but is in the middle at higher resolutions. Someone looking at it might think the cluster has moved when what has actually changed is the relative sizes of the clusters.
