### ISSUE TITLE
non-numeric cluster names

### ISSUE THREAD

**Issue by igordot** [lazappi/clustree#33]
If I would like to use custom cluster labels, is there a way to do that?

Currently, the clusterings have to be numeric. There are a few places in the code where that is explicitly enforced. Since the clusters are discrete values, is it necessary to do that?

**Comment by lazappi** [comment]
Hi @igordot 

Thanks for giving clustree a go.

If I understand you correctly you want to label your clusters using names ("A", "B", "C",...) instead of numbers (1, 2, 3,...)? You are correct that isn't possible at the moment due to checks in the code. It may be possible to change that restriction from numeric to a factor (which would probably make sense). I'm not sure I have time to do that right now but I will look into it.

In the meantime have you seen the `node_label` option in the latest version https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html#adding-labels? You may be able to use that to add the kind of labels you want.

**Comment by igordot** [comment]
Yes, you understood correctly.

I saw the `node_label` option. That seems like the best compromise with the current version. In case you are wondering, my concern is that you essentially have to generate two sets of data and you end up with two labels (the usual numbers and the additional text).

Anyway, I only made this suggestion because I thought it might be a relatively easy fix. If not, I can certainly survive without it.

**Comment by lazappi** [comment]
Cool. I have pushed an update to the develop branch that should let you do this. Here is an example using a text cluster label at `k = 1` on the iris data.

```r
remotes::install_github("lazappi/clustree@develop")
library(clustree)
iris_clusts$K1 <- "A"
clustree(iris_clusts, prefix = "K")
```

![image](https://user-images.githubusercontent.com/6869320/58772722-82d92600-85fd-11e9-85d6-e1be3de72bad.png)

**Comment by igordot** [comment]
That works now. Thanks for the quick fix!

However, this causes a new problem. If you add `node_colour = "sc3_stability"`, the output is discrete values instead of continuous.

**Comment by lazappi** [comment]
Thanks for spotting that, I probably wouldn't have noticed any time soon. I've pushed another develop update to fix it.
