### ISSUE TITLE
Seurat3 reduced dims

### ISSUE THREAD

**Issue by rmenafra** [lazappi/clustree#37]
Hi,
would you mind sharing a practical example on how to access the pca or umap reduction of a Seurat3 object in order to use the cluster_overlay function?
I'm having an hard time implementing what suggested in your documentation: 
".. red_dim must be set to the name of a dimensionality reduction in reducedDimNames(x) (for a SingleCellExperiment) or x@dr (for a Seurat object). x_value and y_value can then be set to red_dimX when red_dim matches the red_dim argument and X is the column of the dimensionality reduction to use"
I tried 
clustree_overlay(seurat.object, "PC_1", "PC_2", prefix = "RNA_snn_res.", red_dim = "pca" , assay = "RNA")
The dimensionality reductions are stored in the seuratobject@reductions and they can be seuratobject@reductions$pca seuratobject@reductions$umap
Thanks in advance

**Comment by lazappi** [comment]
Hi @rmenafra 

Thanks for giving clustree a go! Can you please post some more details of the code you ran and what the error looks like? That will help with working out what the problem is. Details of the versions of Seurat and clustree you are using would also be helpful.

Thanks

**Comment by rmenafra** [comment]
Hi Luke,
I'm using seurat_3.1.1.9005.
The code I tried was in the previous post:
```bash
clustree_overlay(object.subset.1, "PC_1", "PC_2", prefix = "_snn_res.", red_dim = "pca" , assay = "SCT")
```
Error: No data identified for x_value or y_value. Check that red_dim is set correctly.

I can share with you a subset of my seurat object by mail if needed.
Thanks
Roberta

**Comment by lazappi** [comment]
Hi Roberta

Thanks for that. Could you please also paste the output from printing the seurat object? I think there might be a bug in clustree due to some changes in Seurat v3.1 that I wasn't aware of. Hopefully I can track those done. If you can share part of your object with me that would be really helpful. Uploading an Rds file to Google drive/dropbox or similar is probably the easiest.

**Comment by rmenafra** [comment]
Hi Luke,
thanks for your quick reply.
This is an extremely small subset(4 cells), just for you to see the file structure

https://drive.google.com/open?id=17JPeT5wkfHybnUJm4RbKxzYIuTAcEnff
Hope this helps.Best,
Roberta

**Comment by lazappi** [comment]
Hi Roberta

Thanks for the sample dataset, that was really helpful. I think the problem might be what you have set `x_value` and `y_value`. They should be the name of `red_dim` plus the column number you want to use rather than the column name. I know this is a bit convoluted but it was done to handle times when the dimensionality reduction matrix doesn't have column names.

You may also need to change the `prefix` argument. I noticed that the sample object only had one clustering column (`integrated_snn_res.0.5`) but maybe your full dataset has more?

Can you try running the following command and see if that works (and let me know the error if it doesn't):

```r
clustree_overlay(object.subset.1, "pca1", "pca2", red_dim = "pca" , assay = "SCT")
```

I probably should have caught this a bit earlier but I haven't worked on clustree for a while so I'm a bit rusty. Sorry for the delay! 😸

**Comment by rmenafra** [comment]
Hi Luke,
indeed now it works, yes in the original object I had more clustering columns , this was just to give you an example.
Thanks for looking this up.
Best,
Roberta

**Comment by lazappi** [comment]
No worries! 😺 Feel free to open another issue if you have other questions.
