### ISSUE TITLE
clustree_overlay creates missing values (geom_point). 

### ISSUE THREAD

**Issue by tiagobrc** [lazappi/clustree#50]
Hi, Thanks for clustree!
I am trying to plot the overlay with pca/umap but it is not working when doing this command, it runs normally but all points are missing.

`clustree_overlay(SeuratV.3.1.5Obj, assay = "SCT", prefix = "SCT_snn_res.", x_value = "pcaPC_1", y_value = "pcaPC_2", label_nodes = FALSE, red_dim = "pca")`

output:

```
NAs introduced by coercionNAs introduced by coercion
Removed 732 rows containing missing values (geom_point).
Removed 11 rows containing missing values (geom_point).
Removed 18 rows containing missing values (geom_segment).
Removed 8 rows containing missing values (geom_point).
Removed 11 rows containing missing values (geom_segment).
Removed 8 rows containing missing values (geom_point).
Removed 10 rows containing missing values (geom_segment).
Removed 7 rows containing missing values (geom_point).
Removed 9 rows containing missing values (geom_segment).
Removed 6 rows containing missing values (geom_point).
Removed 7 rows containing missing values (geom_segment).
Removed 4 rows containing missing values (geom_point).
Removed 4 rows containing missing values (geom_segment).
Removed 3 rows containing missing values (geom_point).
Removed 3 rows containing missing values (geom_segment).
Removed 3 rows containing missing values (geom_point).
Removed 3 rows containing missing values (geom_segment).
Removed 3 rows containing missing values (geom_point).
Removed 3 rows containing missing values (geom_segment).
Removed 1 rows containing missing values (geom_point).
Removed 54 rows containing missing values (geom_label_repel).
```

And creates empty plot, Clustree function works normally. 

Would this be something easier to figure out?

**Comment by lazappi** [comment]
Hi @tiagobrc 

Thanks for giving **{clustree}** a go! I don't think I have seen this happen before it looks like for some reason you are ending up `NA`s being created. Given that the normal `clustree()` function is working the problem is probably somewhere in the dimensionality reduction part.

Can you please double check that there are no `NA`s in your object (you will probably have other problems if there are but just in case)? If you don't find anything it would be great if you could a subset of your object with me for testing. The smallest amount of data you can get to reproduce this error would be very useful. Please remove any identifying information you don't want to share.

**Comment by trezende21** [comment]
hi @lazappi, 

Thanks for being so solicitous. I don't really know what I did but this error was gone. Weird.

Sorry for wasting your time.


Thanks!
