### ISSUE TITLE
Plot proportion of cells per level as label

### ISSUE THREAD

**Issue by Cumol** [lazappi/clustree#54]
I was wondering how I could plot a label that contains the proportion of cells in the current cluster by resolution/clustering depth.

**Comment by lazappi** [comment]
Hi @Cumol 

Thanks for giving **{clustree}** a go! If I am understanding you correctly you want to add a label with the proportion of the total samples that belong to each cluster (something like `cluster_size / total_samples`)? Every sample should be present at each resolution so `total_samples` should be the same whichever resolution you look at.

This sounds like something that should be easy to do but unfortunately I don't think that it is possible at the moment. It is easy to add the cluster size as a label:

```r
clustree(iris_clusts, prefix = "K", node_label = "size")
```

But I don't think it is possible to do a proportion due to the way the node aggregation functions work. I think I might have a way to make this possible but I need to try some things and see if they work. I will comment here if I am able to come up with a solution.

Thanks for raising the issue 🎉! I hadn't considered this a problem before and I think it's functionality we should have 😸.

**Comment by Cumol** [comment]
Thanks for the quick reply!

I found the solution for "size" and if I understood correctly, "size" is calculated internally, which is why you can pass it as a node label. I was wondering whether the total_samples is also calculated internally and it would be possible to do `node_label = "size/total_samples"`.

Or allow general access to "resolution statistics". I saw another issue where someone calculated the statistics beforehand and then added the values where needed, but that looked too complex for me :D

**Comment by lazappi** [comment]
Yeah, unfortunately that won't work the way things are set up at the moment. I think the workaround I have thought will make that possible but I will have to try and implement it to see.

**Comment by lazappi** [comment]
Ok, my solution didn't work quite as well as I had hoped but I have come up with a slightly hacky workaround for your specific case. Try something like this and see if it gives you what you want.

```r
# You need to replace 150 here with however many samples you have
# I think the only way to do this is to hard code it for now
prop_samples <- function(x) {length(x) / 150}

clustree(YOUR_DATA, prefix = "YOUR_PREFIX", node_label = "ANY_METADATA_COLUMN", 
         node_label_aggr = "prop_samples")
```

**Comment by Cumol** [comment]
Will give it a try and let you know.

**Comment by lazappi** [comment]
@Cumol Was this helpful in the end?

**Comment by plijnzaad** [comment]
I'm not Cumol but yes this works very nicely, I'm using `, node_label_aggr='n_cells', ` with 
`n_cells <- function(x)sprintf("%g cells (%.1f%%)", length(x), 100*length(x)/nrow(df))`
where `df` is the data.frame that is fed to `clustree`. Many thanks!

PS: I was hoping to be able to say `edge_color="black"` (it confuses my users) but that doesn't work for some reason?

**Comment by lazappi** [comment]
> PS: I was hoping to be able to say `edge_color="black"` (it confuses my users) but that doesn't work for some reason?

Please open a new issue if this is a feature you would like to have. At the moment there is no parameter for controlling the edge colour.
