### ISSUE TITLE
Using average stability to optimise clustering resolution

### ISSUE THREAD

**Issue by nbartonicek** [lazappi/clustree#73]
Good day,
We are using the SC3 stability to optimise the resolution used for clustering. More specifically, if:
Ni=number of cells per cluster i
Si=SC3 stability of a cluster
n=total number of cells
total stability = sum(Ni*Si)/n
We then find the resolution in which total stability is the highest. 
Do you see any issues in using this metric to calculate the optimal resolution for clustering of a dataset?
Cheers,
Nenad

**Comment by lazappi** [comment]
Hi @nbartonicek

Thanks for the question! This is an interesting idea which I haven't thought about much. The SC3 stability was mostly implemented as an example and personally, I don't always look at it. In my experience it doesn't always seem to point to the resolution I would select using other things, but that is mostly from looking at it on a clustering tree, not an overall metric like you are describing.

It's definitely worth trying and I would be interested in seeing any results you come up with. I would just be a bit cautious to start with try to confirm the suggested resolution in other ways rather than just trusting the number.
